homepage:
    pattern:  /{_locale}
    defaults: { _controller: lubo_content_manager.page_controller:indexAction, _locale: en }
    requirements:
        _locale: en|fr|de
page:
    pattern: /{_locale}/{slug}
    defaults: { _controller: lubo_content_manager.page_controller:showAction, _locale: en }
    requirements:
        _locale: en|fr|de

